name: Introducing Basic Statistics
category: analysis
authors: ""
shortdesc: This course illustrates how basic statistical concepts can be applied to the analysis of biomolecular simlation data
longdesc: ""
